import { Inter } from 'next/font/google'
import styles from './layout.module.css';
import './globals.css';
import global from '@/global.module.css';
import MobileNavBar from '@/components/Navbar/MobileView/MobileNavBar';
import TopNav from '@/components/Navbar/TopNav';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'shoemato-customer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={global.desktop}>
          <TopNav />
        </div>
        <div className={global.mobile}>
          <MobileNavBar />
        </div>
        {children}
      </body>
    </html>
  )
}

