import React from 'react';
import { Inter } from 'next/font/google';
import './globals.css'
import TopNav from '@/components/Navbar/TopNav';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'shoemato-customer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <TopNav/>
        {children}        
      </body>
    </html>
  )
}
