import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar/Navbar';
import styles from './layout.module.css';
import './globals.css'
import MobileNavBar from '@/components/Navbar/MobileView/MobileNavBar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'shoemato-customer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.navbar}>
        <Navbar/>
        </div>
        <div className={styles.mobileNav}>
        <MobileNavBar/>
        </div>
        {children}
        </body>
    </html>
  )
}

